// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWorkshop.Data;

#nullable disable

namespace TheWorkshop.Migrations
{
    [DbContext(typeof(TheWorkshopContext))]
    [Migration("20240409214911_ItemTypes")]
    partial class ItemTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheWorkshop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("ScrapValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TheWorkshop.Models.Deadline", b =>
                {
                    b.HasBaseType("TheWorkshop.Models.Item");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Deadline");
                });

            modelBuilder.Entity("TheWorkshop.Models.Event", b =>
                {
                    b.HasBaseType("TheWorkshop.Models.Item");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("TheWorkshop.Models.ToDoTask", b =>
                {
                    b.HasBaseType("TheWorkshop.Models.Item");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
